name: Build

on:
  workflow_call:
    inputs:
      enable-checks:
        default: true
        description: "Enable validations"
        required: false
        type: boolean
      version:
        required: true
        type: string

env:
  JAVA_DISTRIBUTION: "corretto"
  JAVA_VERSION: "17"

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run validations
        if: ${{ inputs.enable-checks }}
        run: ./gradlew test
