name: Main

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.sha }}
